# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis-gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvisgui(object):
    def setupUi(self, jarvisgui):
        jarvisgui.setObjectName("jarvisgui")
        jarvisgui.resize(749, 439)
        self.centralwidget = QtWidgets.QWidget(jarvisgui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 751, 441))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setMouseTracking(False)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../resources/jarvis-intro-1.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.runAssistant = QtWidgets.QPushButton(self.centralwidget)
        self.runAssistant.setGeometry(QtCore.QRect(480, 390, 151, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.runAssistant.setFont(font)
        self.runAssistant.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.runAssistant.setFocusPolicy(QtCore.Qt.NoFocus)
        self.runAssistant.setAutoFillBackground(False)
        self.runAssistant.setStyleSheet("color: rgb(82, 135, 87);")
        self.runAssistant.setFlat(True)
        self.runAssistant.setObjectName("runAssistant")
        self.putToSleep = QtWidgets.QPushButton(self.centralwidget)
        self.putToSleep.setGeometry(QtCore.QRect(650, 390, 91, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.putToSleep.setFont(font)
        self.putToSleep.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.putToSleep.setStyleSheet("color: rgb(87, 36, 115);")
        self.putToSleep.setFlat(True)
        self.putToSleep.setObjectName("putToSleep")
        self.date = QtWidgets.QTextBrowser(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(20, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(14)
        self.date.setFont(font)
        self.date.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.date.setAutoFillBackground(False)
        self.date.setStyleSheet("background:transparent;\n"
"border:none;")
        self.date.setObjectName("date")
        self.time = QtWidgets.QTextBrowser(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(540, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(14)
        self.time.setFont(font)
        self.time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time.setAutoFillBackground(False)
        self.time.setStyleSheet("background:transparent;\n"
"border:none;")
        self.time.setObjectName("time")
        jarvisgui.setCentralWidget(self.centralwidget)

        self.retranslateUi(jarvisgui)
        QtCore.QMetaObject.connectSlotsByName(jarvisgui)

    def retranslateUi(self, jarvisgui):
        _translate = QtCore.QCoreApplication.translate
        jarvisgui.setWindowTitle(_translate("jarvisgui", "J.A.R.V.I.S"))
        self.runAssistant.setText(_translate("jarvisgui", "J.A.R.V.I.S"))
        self.putToSleep.setText(_translate("jarvisgui", "Sleep"))
        self.date.setHtml(_translate("jarvisgui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Baskerville Old Face\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ababab;\">Date:</span></p></body></html>"))
        self.time.setHtml(_translate("jarvisgui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Baskerville Old Face\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ababab;\">Time:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvisgui = QtWidgets.QMainWindow()
    ui = Ui_jarvisgui()
    ui.setupUi(jarvisgui)
    jarvisgui.show()
    sys.exit(app.exec_())
